### ISSUE TITLE
Differentiate between owned and watched accounts in drop down selector

### ISSUE THREAD

**Issue by asnaith** [ChainSafe/Multix#176]
When you watch an account eg ```5Fer9CC593nS2JTsS4SFC3iWT7M2cwcVWqixjAQ9uPDKg8Jg``` all of the pure's and multisigs that the address is behind will also appear as options in the drop-down selector. 

The issue here is that is confusing for a user to know which addresses belong to their own setup and which come from an account that is being watched. 

<img width="1277" alt="Screenshot 2023-05-24 at 11 15 00 AM" src="https://github.com/ChainSafe/Multix/assets/3982665/9efe17de-110e-4557-ac92-d5c88e0f2710">

It would be good to differentiate in the list which addresses are being watched from the addresses that are part of the user's own setup. Perhaps with an eye or telescope emoji. 

Background: 

"There's no way to know what multisig/pure proxy a user want to see.
I think the confusion could be lowered if we could show clearly that the reason an account is in the dropdown is because of a watched account? The only way I would find easy to understand would be with :eyes: emoji next to the identicon or something :)"

_Originally posted by @Tbaut in https://github.com/ChainSafe/Multix/issues/161#issuecomment-1560182488_

**Comment by Tbaut** [comment]
I think one cool way to have this and still be subtle would be to add after or before the batch, an eye outlines icon (inside the badge style still) `HiOutlineEye` from https://react-icons.github.io/react-icons/icons?name=hi2
![image](https://github.com/ChainSafe/Multix/assets/33178835/fb55ab8e-26c1-49d9-8494-a5c4374abcdb)

ideally, and if that's working well, we could have a tooltip that would tell "watched account" or something. I'm not a fan of tooltips because it's not great for mobile, but it's insignificant enough for this one.
