### ISSUE TITLE
Update all buttons design in the project

### ISSUE THREAD

**Issue by Lykhoyda** [ChainSafe/Multix#200]
Scenario: All the buttons and links components should be updated with the new UI component from #189 
Given: All pages of the project
When: User interacts with Button or Link
Then: The design should correspond to the new design from Figma https://www.figma.com/file/4dQC9kxf5uxCrAjpkzAK0D/Multix?type=design&node-id=229-12512&t=NpmL9FmHrgq6g8Yi-0

**Comment by Tbaut** [comment]
You've been quicker than me to push a PR. Since I've done it, let me tell the inconsistencies I've identified, and see if we can tackle them.
While the design in Figma doesn't have everything, here is what I've found is inconsistent with the design:

- This button is gray and doesn't fit with the design, it should be a secondary (white bg) button. This also applies to the multisig creation flow.
![image](https://github.com/ChainSafe/Multix/assets/33178835/9088536c-242f-474d-9936-9697550b6fd8)

- the Back/Next should be secondary/primary buttons, not links
![image](https://github.com/ChainSafe/Multix/assets/33178835/c191df6a-814a-487b-b0cb-41df5e6a82a0)

- We should primary/secondary buttons here:
![image](https://github.com/ChainSafe/Multix/assets/33178835/bfa42c65-2aca-4251-8271-f5dc46c25a06)

- All the modals should use the new buttons, e.g
![image](https://github.com/ChainSafe/Multix/assets/33178835/e1f35ed0-df2b-4e29-b1a1-eafee7349c53)

- the Multisig change modal already has the new ones, but we should use primary/secondary
![image](https://github.com/ChainSafe/Multix/assets/33178835/0a33f787-9eb6-4793-84f5-610627129f4c)
