### ISSUE TITLE
support pureproxies for multisig creation/mgmt

### ISSUE THREAD

**Issue by hitchhooker** [ChainSafe/Multix#578]
currently multix requires at least one "local" account as participant in multisig and wont allow proxy controls

**Comment by Tbaut** [comment]
Right, to create a multisig you need to be a signatory. You can watch any multisig/proxy though using the Settings>Watch account.
I'm not sure I understand the second part of your question.

Multix is a tool for multisigs, it's not aimed at being a general purpose wallet. So we're trying to support anything related to multisigs and proxy controlled by a multisig, but not more.

**Comment by Tbaut** [comment]
oh I understand maybe. You mean that you can't have a
- account -> pure proxy -> signatory of a multisig. Is that it?

In that case, yes this is a limitation because I believe that such constructs are a super niche. The construct with a simple multisig controlling a pure is more transparent to all users, since a key change in the signatories needs a re-approval by the threshold of signatories. I do undertsand it may not be sufficient in very specific cases, but making the application more complex, and hence less maintainable for this reason. It's a trade off we have to take :(

**Comment by hitchhooker** [comment]
![image](https://github.com/user-attachments/assets/3e791e52-1443-49a5-8459-5daa2fb68fd9)
yes exactly that. it was possible to do via polkadotjs, but quite a footgun.

spending countless hours today setting up IdentityJudgement right proxy on people-paseo to multisig without success we end up dropping the initial multisig draft and just use direct signer to control multisig and rotate new multisig to control final pureproxy if changes required.
