### ISSUE TITLE
Display multisig proposals sorted by time

### ISSUE THREAD

**Issue by Tbaut** [ChainSafe/Multix#82]
Right now, I the proposals are displayed randomly (it seems).
We have the information for each proposal regarding when it was actually proposed.
It would be nice to
- sort the proposals by date
- show the date

While we may not have the date from the indexer (the `MultisigCall` entity has it but the source of truth should be the blockchain). We have the ability to query this information for the block in which the call was made, there should be a `timestamp` param.

**Comment by dj-pundir** [comment]
Hey @Tbaut  In order to look into this issue, i am not able to proceed after below:

![image](https://user-images.githubusercontent.com/61174028/231942345-cc9bda17-0052-4f5a-9c56-111dd8f4a14b.png)

So i can run the app and connect to polkadot ext wallet. and when select the account the Next button is disabled.

**Comment by dj-pundir** [comment]
Hey @Tbaut  I was trying to look the above issue but may be i am not seeing the exact page or i am missing some steps to reproduce this. I have borrowed some rococo and created a Multisig then see this proposal page:

![image](https://github.com/ChainSafe/Multix/assets/61174028/4d93efd9-2105-442c-a9f1-509cc771fed0)

Let me know if i have to follow something else. Thanks!!
